version: "3"
services:
  db:
    container_name: scs-db
    platform: linux/x86_64 # se estiver usando windows, comente essa linha com #
    image: mariadb:10.3.38
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=P@$$$$w0rd
      - MYSQL_DATABASE=scs
      - MYSQL_USER=scs
      - MYSQL_PASSWORD=Siop@2024
    ports:
      - 3336:3306
    expose:
      - 3336
    volumes:
      - data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
  nginx:
    container_name: scs-nginx
    image: nginx:latest
    ports:
      - 8080:80
    networks:
      - internal
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  php:
    container_name: scs-php
    build: ./php
    networks:
      - internal
    volumes:
      - ./html/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
networks:
  internal:
    driver: bridge
volumes:
  data: