version: "3"
services:
  db:
    container_name: scs-db
    platform: linux/x86_64 # se estiver usando windows, comente essa linha com #
    image: mysql:8
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - TZ=$TZ
    ports:
      - $MYSQL_PORT:${MYSQL_LOCAL_PORT:-3306}
    expose:
      - $MYSQL_PORT
    networks:
      scs-network:
        ipv4_address: 192.168.2.10
    volumes:
      - data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
  nginx:
    container_name: scs-nginx
    image: nginx:latest
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      scs-network:
        ipv4_address: 192.168.2.11
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  php:
    container_name: scs-php
    build: ./php
    env_file: .env
    networks:
      scs-network:
        ipv4_address: 192.168.2.12
    environment:
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - TZ=$TZ
      - MAIL_SMTP=$MAIL_SMTP
      - MAIL_SMTP_NAME=$MAIL_SMTP_NAME
      - MAIL_SMTP_USER=$MAIL_SMTP_USER
      - MAIL_SMTP_PASS=$MAIL_SMTP_PASS
      - MAIL_SMTP_CRYPTO=$MAIL_SMTP_CRYPTO
      - MAIL_SMTP_PORT=$MAIL_SMTP_PORT
      - SESSION_TIMEOUT=$SESSION_TIMEOUT
      - SESSION_SECRET=$SESSION_SECRET
    volumes:
      - ./html/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
networks:
  scs-network:
    external: true

volumes:
  data: